name: Build JDK 25 for iOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_iosport:
    name: "Build Java 25 for iOS aarch64"
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up boot JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Build with CI build script
        run: |
          export BUILD_IOS=1
          export TARGET_VERSION=25
          bash "1_ci_build_arch_aarch64.sh"

      - name: Upload JRE build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre25-ios-aarch64"
          path: jre25-ios*.tar.xz

      - name: Upload JRE debuginfo build output
        uses: actions/upload-artifact@v4
        with:
          name: "jre25-ios-debuginfo-aarch64"
          path: dizout
